---

# tasks file for roles/nginx
- name: Install nginx
  yum:
    name: nginx, curl
    state: present
    update_cache: true
  register: first_task

- name: Remove default config file
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "/etc/nginx/conf.d/default.conf"
  - "/etc/nginx/nginx.conf"
  when: first_task.changed == true

- name: Create new dir for vhost
  file:
    path: "{{ item }}"
    recurse: yes
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
  - "/etc/nginx/sites-available"
  - "/etc/nginx/sites-enabled"
  when: first_task.changed == true

- name: Install vhost
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
  - { src: "default_vhost.conf.j2", dest: "/etc/nginx/sites-available/default_vhost.conf" }
  - { src: "nginx.conf.j2", dest: "/etc/nginx/nginx.conf" }
  notify: reload_nginx

- name: Create symbolinc link
  file: 
    src: /etc/nginx/sites-available/default_vhost.conf
    dest: /etc/nginx/sites-enabled/default_vhost.conf
    state: link

- name: Start nginx
  command: nginx -g 'daemon on;'
  when: first_task.changed == true
  # systemd:
  #   name: nginx
  #   state: started

- name: Flush handlers
  meta: flush_handlers