    all:
      children:
      
        #serveur RHEL
        servers:
          children:
            nginx:
              hosts:
                172.18.0.2:
                
            webserver:
              hosts:
                172.18.0.3:
  
      vars:
        #ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_pass: "rootpass"
        nginx_ip: 172.18.0.2
        webserv_ip: 172.18.0.3
